wallpaper {
  monitor = eDP-1
  path = $HOME/.config/hypr/wallpapers/Custom2.jpg 
  fit_mode= cover
}

wallpaper {
  monitor = DP-3
  path = $HOME/.config/hypr/wallpapers/Custom2.jpg 
  fit_mode = cover
}

wallpaper {
  monitor = 
  path =  $HOME/.config/hypr/wallpapers/Custom2.jpg 
  fit_mode = cover
}

splash = true
