background {
	path = $HOME/.config/hypr/wallpapers/frierenShrek.jpg
}

input-field {
    size = 325, 35
    position = 0, -250
    outline-thickness = 10
    font_family = HeavyData Nerd Font
    placeholder_text = enter password
    dots-size = 0.1
    inner_color = rgba(255,255,255,0.1)
    outer_color = rgba(255,255,255,0.5)

}

label {
    text = $TIME
    font_size = 150
    font_family = HeavyData Nerd Font
    position = 0, 400
}




